import { useEffect, useState } from "react";
import { Bell } from "lucide-react";
import api from "../lib/api";
import type { Alert } from "../lib/types";

export default function AlertsPage() {
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [loading, setLoading] = useState(true);
  const [severity, setSeverity] = useState<string>("");
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const fetchAlerts = async () => {
    try {
      const params: Record<string, string> = {};
      if (severity) params.severity = severity;
      const resp = await api.get<Alert[]>("/alerts", { params });
      setAlerts(resp.data);
    } catch (err) {
      console.error("Alerts fetch error:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAlerts();
  }, [severity]);

  if (loading) {
    return (
      <div className="loading-screen" style={{ minHeight: "50vh" }}>
        <div className="loading-spinner" />
      </div>
    );
  }

  return (
    <div className="fade-in">
      <div className="page-header">
        <h1>
          <Bell
            size={24}
            style={{ display: "inline", marginRight: "0.5rem" }}
          />
          Alert History
        </h1>
        <p>All alerts generated by Watcha agent</p>
      </div>

      {/* Filters */}
      <div className="filters-bar">
        {["", "critical", "warning", "info"].map((sev) => (
          <button
            key={sev}
            className={`btn ${severity === sev ? "btn-primary" : "btn-secondary"}`}
            onClick={() => setSeverity(sev)}
            style={{ padding: "0.45rem 1rem", fontSize: "0.8rem" }}
          >
            {sev || "All"}
          </button>
        ))}
      </div>

      {/* Alerts List */}
      {alerts.length > 0 ? (
        <div
          style={{ display: "flex", flexDirection: "column", gap: "0.75rem" }}
        >
          {alerts.map((alert) => (
            <div
              key={alert.id}
              className="alert-card glass-card"
              onClick={() =>
                setExpandedId(expandedId === alert.id ? null : alert.id)
              }
            >
              <div className="alert-header">
                <span className={`severity-badge ${alert.severity}`}>
                  {alert.severity}
                </span>
                {alert.asset_symbol && (
                  <span
                    style={{
                      color: "var(--text-muted)",
                      fontSize: "0.8rem",
                    }}
                  >
                    {alert.asset_symbol}
                  </span>
                )}
                {alert.sentiment && (
                  <span
                    style={{
                      marginLeft: "auto",
                      fontSize: "0.8rem",
                      color:
                        alert.sentiment === "bullish"
                          ? "var(--accent-emerald)"
                          : alert.sentiment === "bearish"
                            ? "var(--accent-rose)"
                            : "var(--text-muted)",
                    }}
                  >
                    {alert.sentiment === "bullish"
                      ? "📈"
                      : alert.sentiment === "bearish"
                        ? "📉"
                        : "➡️"}{" "}
                    {alert.sentiment}
                  </span>
                )}
              </div>
              <div className="alert-title">{alert.title}</div>

              {expandedId === alert.id && alert.ai_analysis && (
                <div
                  className="alert-body"
                  style={{ marginTop: "0.5rem" }}
                >
                  {alert.ai_analysis}
                </div>
              )}

              <div className="alert-meta">
                {alert.impact_score && (
                  <span>Impact: {alert.impact_score}/10</span>
                )}
                <span>
                  {alert.telegram_sent ? "✅ Sent to Telegram" : "📵 Not sent"}
                </span>
                <span>{new Date(alert.created_at).toLocaleString()}</span>
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="empty-state glass-card">
          <div className="icon">🔔</div>
          <p>
            {severity
              ? `No ${severity} alerts found.`
              : "No alerts yet. Start the agent to begin monitoring."}
          </p>
        </div>
      )}
    </div>
  );
}
